config/routes.rb
Rails.application.routes.draw do
  # respond to root for load balancer health checks
  get '/', to: proc { [200, {}, ['OK']] }

  get '/400' => 'errors#bad_request'

  get '/404' => 'errors#not_found'

  get '/500' => 'errors#internal_server_error'

  get 'users/:id/unsubscribe/new' => 'users#new_unsubscribe'
  post 'users/:id/unsubscribe/create' => 'users#create_unsubscribe'

  resources :suppressions, except: [:show, :edit, :update, :destroy]

  # catch all route
  match ':all' => 'errors#not_found', via: [:all]
end

app/views/jira_status/show_status_for_commit.html.erb
<%= form_for :suppression, url: suppressions_path do |f| %>

<div class="container">
  TODO: Show the tags on the commit, autobahn clean, build clean
  <%case @push.status%>
  <%when Github::Api::Status::STATE_PENDING.to_s%>
    <div class="alert alert-warning">
      Push is being processed, please refresh in a moment
    </div>
  <%when Github::Api::Status::STATE_SUCCESS.to_s%>
    <div class="alert alert-success">
      Push passed all checks
    </div>
  <%when Github::Api::Status::STATE_FAILED.to_s%>
    <div class="alert alert-danger">
      Warning: Branch is not ready to deploy.<br>
      <ul>
      <%get_combined_error_counts.each do |error_object, error_counts|%>
          <%error_counts.each do |error_code, count|%>
            <li><%=count%> <%=map_error_code_to_message(error_object, error_code)%>
        <%end%>
      <%end%>
      </ul>
    </div>
  <%end%>
  <%if @push.has_jira_issues%>
    <h4><%=@push.jira_issues.count%> JIRA issues(s) in this branch</h4>
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Ignore</th>
        <th>Key</th>
        <th>Last SHA</th>
        <th>Assignee</th>
        <th>Status</th>
        <th>Deploy Date</th>
        <th>Summary</th>
      </tr>
      </thead>
      <tbody>
      <%@push.jira_issues.each do |jira_issue|%>
        <tr class="<%='danger' if jira_issue.has_unignored_errors?(@push)%>">
          <td><input type="checkbox"></td>
          <td nowrap>
            <%if jira_issue.parent_issue %>
              <%=link_to(jira_issue.parent_issue.key, jira_url_for_issue(jira_issue.parent_issue), target: '_blank')%><br/>&#8627;
            <%end%>
            <%=link_to(jira_issue.key, jira_url_for_issue(jira_issue), target: '_blank')%>
          </td>
          <td><%=link_to(jira_issue.latest_commit.short_sha, github_url_for_commit(jira_issue.latest_commit), target: '_blank')%></td>
          <td nowrap><%=jira_issue.assignee.name%></td>
          <td nowrap><%=jira_issue.status%></td>
          <td nowrap><%=jira_issue.targeted_deploy_date || '-'%></td>
          <td><%=jira_issue.summary%></td>
        </tr>
      <%end%>
      </tbody>
    </table>
  <%end%>

  <%if @push.has_orphan_commits%>
    <h4><%=@push.orphan_commits.count%> Commit(s) with no JIRA, or invalid, issue number</h4>
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Ignore</th>
        <th>SHA</th>
        <th>Author Name</th>
        <th>Commit Message</th>
      </tr>
      </thead>
      <tbody>
      <%@push.orphan_commits.each do |commit|%>
        <tr class="<%='danger' if commit.has_unignored_errors?(@push)%>">
          <td><input type="checkbox"></td>
          <td><%=link_to(commit.short_sha, github_url_for_commit(commit), target: '_blank')%></td>
          <td nowrap><%=commit.author.name%></td>
          <td><%=commit.message%></td>
        </tr>
      <%end%>
      </tbody>
    </table>
  <%end%>
  <%if false%>
    <h4>JIRA issues ready to deploy, but not in this branch</h4>
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Ignore</th>
        <th>Key</th>
        <th>Last SHA</th>
        <th>Assignee</th>
        <th>Status</th>
        <th>Deploy Date</th>
        <th>Summary</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td><input type="checkbox" checked></td>
        <td><a href="#">STORY-4533</a></td>
        <td><a href="#">aaf2ef4</a></td>
        <td>Yo Biziiac</td>
        <td>Ready to Deploy</td>
        <td>11/27/2016</td>
        <td>Description for ya</td>
      </tr>
      <tr class="danger">
        <td><input type="checkbox"></td>
        <td><a href="#">STORY-9999</a></td>
        <td><a href="#">bbf2ef4</a></td>
        <td>Dave Lamo</td>
        <td>Ready to Deploy</td>
        <td>11/30/2016</td>
        <td>The thingermahowzer</td>
      </tr>
      </tbody>
    </table>
  <%end%>
  Save Ignore and Update Status Button --
  Refresh JIRA Data Button
  Copy/Paste deploy list
</div>
<% end %>